</div> <!-- #main-container -->

<div id="banner">
    <div><img src="/assets/icons/logo-white.svg" alt="logo"></div>
    <div>
        <h1>Nero Ossidiana</h1>
    </div>
</div>

<footer class="accordion" id="footer-accordion">
    <!-- row -->
    <div id="footer-inner-cont" class="container">

        <div class="footer-card" id="footer-contact-us">
            <div class="section-header" id="headingOne">
                <div class="icon-cont"><i class="fa fa-envelope-o" style="font-size: 1.8em;"></i></div>
                <div class="btn-cont">
                    <button class="btn collapsed no-focus" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseTwo">Contattaci</button>
                    <div class="icon-cont chev-cont"><i class="fa fa-chevron-up" style="font-size: 1.3em;"></i></div>
                </div>
                <p class="header">Contattaci</p>
                <!-- <i class="chevron"></i> -->
            </div>

            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#footer-accordion">
                <div class="section-body card-body">
                    <p>Italia</p>
                    <p>999 999999</p>
                    <p>Mar - Ven | 9:00 - 17:00</p>
                    <p>Sab | 9:00 - 17:00</p>
                    <p class="link"><a class="text-dark" href="/Contattaci">nero_ossidiana@support.com</a></p>
                </div>
            </div>
        </div>

        <div class="footer-card" id="footer-support">
            <div class="section-header" id="headingTwo">
                <div class="icon-cont"><i class="fa fa-question-circle" style="font-size: 2em;"></i></div>
                <div class="btn-cont">
                    <button class="btn collapsed no-focus" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Supporto</button>
                    <div class="icon-cont chev-cont"><i class="fa fa-chevron-up" style="font-size: 1.3em;"></i></div>
                </div>
                <p class="header">Supporto</p>
                <!-- <i class="chevron"></i> -->
            </div>

            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#footer-accordion">
                <div class="section-body card-body">
                    <p class="link"><a class="text-dark" href="/Supporto/FAQ">FAQ</a></p>
                    <p class="link"><a class="text-dark" href="/Supporto/Taglie">Taglie</a></p>
                    <p class="link"><a class="text-dark" href="/Supporto/Consegna">Consegna</a></p>
                    <p class="link"><a class="text-dark" href="/Supporto/Politica-sui-resi">Politica sui resi</a></p>
                    <p class="link"><a class="text-dark" href="/Supporto/Informativa-sulla-privacy">Informativa sulla privacy</a></p>
                    <p class="link"><a class="text-dark" href="/Supporto/Diritto-di-recesso">Diritto di recesso</a></p>
                    <p class="link"><a class="text-dark" href="/Supporto/Termini-e-condizioni">Termini e condizioni</a></p>
                    <p class="link"><a class="text-dark" href="/Supporto/Promozioni-e-offerte">Promozioni e offerte</a></p>
                </div>
            </div>
        </div>

        <div class="footer-card" id="footer-about-us">
            <div class="section-header" id="headingThree">
                <div class="icon-cont"><i class="fa fa-info" style="font-size: 2em;"></i></div>
                <div class="btn-cont">
                    <button class="btn collapsed no-focus" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseTwo">Chi siamo</button>
                    <div class="icon-cont chev-cont"><i class="fa fa-chevron-up" style="font-size: 1.3em;"></i></div>
                </div>
                <p class="header">Chi siamo</p>
                <!-- <i class="chevron"></i> -->
            </div>

            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#footer-accordion">
                <div class="section-body card-body">
                    <p class="link"><a class="text-dark" href="/Chi-Siamo">Azienda</a></p>
                </div>
            </div>
        </div>

        <!-- row -->
        <div id="additional-info">
            <div id="copyright">
                <p>All rights reserved <i></i> Nero Ossidiana <span>2019</span></p>
            </div>
            <div id="other-links">
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-instagram"></i></a>
                <a href="#"><i class="fa fa-pinterest"></i></a>
                <a href="#"><i class="fa fa-twitter-square"></i></a>
                <a href="#"><i class="fa fa-youtube"></i></a>
                <a href="#"><i class="fa fa-facebook-square"></i></a>
            </div>
        </div>
    </div>
</footer>

<script id="main-script" type="text/javascript" src="/assets/dist/main.bundle.js" defer></script>

</body>

</html>