<?php include "views/shared/header.phtml"; ?>

<section id="checkout" class="container">
    <form action="/Checkout" method="POST" class="needs-validation" id="checkout-form" novalidate>
        <div id="cont1">
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <input type="text" class="form-control rounded-0" id="first-name" placeholder="Nome" value="<?php echo isset($_SESSION["Customer"]["FirstName"]) ? $_SESSION["Customer"]["FirstName"] : '' ?>" name="FirstName" required pattern="^[a-zA-Z]+(( {1}[a-zA-Z]+)+)?$">
                    <div class="invalid-feedback"></div>
                </div>
                <div class="col-md-6 mb-3">
                    <input type="text" class="form-control rounded-0" id="last-name" placeholder="Cognome" value="<?php echo isset($_SESSION["Customer"]["LastName"]) ? $_SESSION["Customer"]["LastName"] : '' ?>" name="LastName" required pattern="^[a-zA-Z]+(( {1}[a-zA-Z]+)+)?$$">
                    <div class="invalid-feedback"></div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-12 mb-3">
                    <div class="input-group">
                        <input type="email" class="form-control rounded-0" id="email" placeholder="La tua email" value="<?php echo isset($_SESSION["Customer"]["Email"]) ? $_SESSION["Customer"]["Email"] : '' ?>" name="Email" aria-describedby="inputGroupPrepend" required>
                        <div class="invalid-feedback"></div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-9 mb-3">
                    <input type="text" class="form-control rounded-0" id="address" placeholder="Il tuo indirizzo" value="<?php echo isset($_SESSION["Customer"]["Address1"]) ? $_SESSION["Customer"]["Address1"] : '' ?>" name="Address1" required pattern="^[a-zA-Z]+(( {1}[a-zA-Z]+)+)?$">
                    <div class="invalid-feedback"></div>
                </div>
                <div class="col-md-3 mb-3">
                    <input type="text" class="form-control rounded-0" id="address-num" placeholder="N°" value="<?php echo isset($_SESSION["Customer"]["Address1Num"]) ? $_SESSION["Customer"]["Address1Num"] : '' ?>" name="Address1Num" required pattern="^[0-9]+$">
                    <div class="invalid-feedback"></div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-12 mb-3">
                    <input type="text" class="form-control2 rounded-0" id="address2" placeholder="Indirizzo di fatturazione alternativo" value="<?php echo isset($_SESSION["Customer"]["Address2"]) ? $_SESSION["Customer"]["Address2"] : '' ?>" name="Address2" pattern="^[\w]+( {1}[\w]+)+ {1}[0-9]+?$">
                    <div class="invalid-feedback"></div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-9 mb-3">
                    <input type="text" class="form-control rounded-0" id="city" placeholder="Città" value="<?php echo isset($_SESSION["Customer"]["City"]) ? $_SESSION["Customer"]["City"] : '' ?>" name="City" required pattern="^[a-zA-Z]+(( {1}[a-zA-Z]+)+)?$">
                    <div class="invalid-feedback"></div>
                </div>
                <div class="col-md-3 mb-3">
                    <input type="text" class="form-control2 rounded-0" id="post-code" value="<?php echo isset($_SESSION["Customer"]["ZipCode"]) ? $_SESSION["Customer"]["ZipCode"] : '' ?>" placeholder="CAP" name="ZipCode" required pattern="^[0-9]+$">
                    <div class="invalid-feedback"></div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <select class="custom-select rounded-0" id="countries" name="Country" required>
                        <option value="" <?php echo !isset($_SESSION["Customer"]["Country"]) ? 'selected' : '' ?>>Paese</option>
                        <?php foreach ($countries as $country) {
                            $country = (explode(":", trim($country)))[1]; ?>
                        <option value="<?= $country ?>" <?php echo isset($_SESSION["Customer"]["Country"]) && $_SESSION["Customer"]["Country"] == $country ? 'selected' : '' ?>><?= $country ?></option>
                        <?php 
                    } ?>
                    </select>
                    <div class="invalid-feedback"></div>
                </div>
                <div class="col-md-6 mb-3">
                    <input type="text" class="form-control rounded-0" id="telephone" placeholder="Telefono" name="Phone" pattern="^[0-9]+([ |\-|/]{1}[0-9]+)?$">
                    <div class="invalid-feedback"></div>
                </div>
            </div>
            <div class="form-group row justify-content-center">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                    <label class="form-check-label" for="invalidCheck">
                        Agree to terms and conditions
                    </label>
                    <div class="invalid-feedback">
                        You must agree before submitting.
                    </div>
                </div>
            </div>
        </div>

        <div id="cont2-wrapper">
            <div id="cont2">
                <div id="subtotal" class="flex">
                    <p>Subtotale (<?= count($_SESSION["Cart"]) ?> Articoli)</p>
                    <p><?=$total ?>€</p>
                </div>
                <div id="delivery-costs-2" class="flex">
                    <p>Spedizione</p>
                    <p>+ <?=$shippingCosts ?></p>
                </div>
                <div id="total-2" class="flex">
                    <p>Totale</p>
                    <p><?=$total + $shippingCosts ?>€</p>
                </div>
                <div class="row justify-content-center">
                    <button class="btn btn-white rounded-0" id="submit-btn" type="submit">Procedi al pagamento</button>
                </div>
            </div>
        </div>

    </form>
</section>

<script src="/assets/js/checkout.js"></script>

<?php include "views/shared/footer.phtml"; ?> 