<?php include "views/shared/header.phtml"; ?>

<section id="contact-us" class="container">
    <h1>Contatti</h1>
    <div id="form-wrapper">
        <form action="/Contattaci" method="POST" novalidate>
            <div class="form-group">
                <label for="name">Nome:</label>
                <input type="text" class="form-control rounded-0" id="name" placeholder="Marco Rossi" pattern="^[a-zA-Z]+(( {1}[a-zA-Z]+)+)?$" required>
                <div class="invalid-feedback"></div>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control rounded-0" id="email" placeholder="example@gmail.com" required>
                <div class="invalid-feedback"></div>
            </div>
            <div class="form-group">
                <label for="objext">Oggetto:</label>
                <input type="text" class="form-control rounded-0" id="object" placeholder="Informazione" required>
                <div class="invalid-feedback"></div>
            </div>
            <div class="form-group">
                <label for="message">Messaggio:</label>
                <textarea class="form-control rounded-0" id="message" rows="5" required></textarea>
                <div class="invalid-feedback"></div>
            </div>
            <div class="btn-cont">
                <button type="submit" class="btn btn-dark">Invia</button>
            </div>
        </form>
    </div>
</section>

<script src="/assets/js/contact-us.js"></script>

<?php include "views/shared/footer.phtml"; ?>