<?php include "views/shared/header.phtml"; ?>

<section id="login" class="row justify-content-center align-items-start" class="container">
    <div id="login-cont">
        <form action="/Login" method="POST" class="needs-validation" novalidate>
            <h2 class="text-center">Login</h2>
            <div class="form-group">
                <label for="email">Indirizzo Email</label>
                <input type="email" class="form-control rounded-0" id="email" aria-describedby="email" name="email" placeholder="Inserisci email" value="" required>
                <div class="invalid-feedback"></div>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control rounded-0" id="password" name="password" placeholder="Password" required>
                <div class="invalid-feedback"></div>
            </div>
            <div class="row justify-content-center">
                <button id="login-btn" type="submit" class="rounded-0 btn btn-white col-6">Accedi</button>
            </div>
            <?php if ($error) { ?>
            <div class="row justify-content-center">
                <p class="error"><?= $error ?></p>
            </div>
            <?php } ?>
        </form>
        <div id="partition">
            <hr>
            <span class="center-align">Non possiedi un profilo?</span>
        </div>
        <div class="row justify-content-center">
            <a href="/Crea-Profilo" class="rounded-0 btn btn-dark col-6">Crea Profilo</a>
        </div>
    </div>
</section>

<script src="/assets/js/login.js"></script>

<?php include "views/shared/footer.phtml"; ?> 