<?php include "views/shared/header.phtml"; ?>

<script src="/assets/js/components/_product.component.js" type="text/javascript"></script>
<?php echo "<script>var prodDetails = " . json_encode($prodDetails) . "</script>"; ?>

<section id="prod-details" class="container">

    <div class="modal fade" id="product-details-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">L'articolo è stato aggiunto al carrello</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div><img src="<?= "\assets\images\\" . $product["Images"][0] ?>" alt="modal product image"></div>
                    <div>
                        <div id="modal-prod-name">
                            <p><?= $product["Name"]; ?></p>
                        </div>
                        <div id="modal-quantity">
                            <p><span>Quantity: </span><span><?= end($_SESSION["Cart"])->quantity; ?></span></p>
                        </div>
                    </div>
                    <div>
                        <p>
                            <span id="modal-price" class="<?= $product["Discount"] ? "line-through" : "highlight" ?>"><?= $product["Price"] ?>€</span>
                            <?php if ($product["Discount"]) { ?>
                                <span id="modal-discounted-price" class="highlight"><?= $product["EndPrice"] ?>€</span>
                            <?php } ?>
                        </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="/Carrello" type="button" class="rounded-0 btn btn-dark">Vai al carrello</a>
                    <button onclick="$('#product-details-modal').modal('hide');" class="rounded-0 btn btn-white">Continua i tuoi acquisti</button>
                </div>
            </div>
        </div>
    </div>

    <div id="img-modal">
        <i class="fa fa-times"></i>
        <div id="modal-img-cont">
            <img id="img">
        </div>
        <div id="modal-img-nav">

            <?php $y = 0;
            foreach ($product["Images"] as $imageUrl) { ?>

                <div class="img-canvas <?php echo ($y === 0) ? "active" : ""; ?>" style="background-image: url('/assets/images/<?= $imageUrl ?>')"></div>

                <?php $y++;
            } ?>

        </div>
    </div>

    <div id="cont">
        <h2 id="prod-title"><?= $product["Name"] ?></h2>
    </div>

    <div id="cont1">
        <div id="img-cont">
            <div id="carouselControls" class="carousel slide" data-pause="true">
                <div class="carousel-inner">
                    <?php
                    $i = 0;
                    foreach ($product["Images"] as $imageUrl) { ?>
                        <div class="carousel-item <?php echo ($i === 0) ? "active" : ""; ?>">
                            <img src=<?= "/assets/images/$imageUrl" ?> class="carousel-img d-block" alt="product image">
                        </div>
                        <?php $i++;
                    } ?>
                </div>
                <?php if (count($product["Images"]) > 1) { ?>
                    <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
                        <span class="car-icon" id="car-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
                        <span class="car-icon" id="car-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                <?php } ?>
            </div>
        </div>
        <div id="img-car-cont">
            <div id="owl-carousel-cont">
                <div class="imgs-view-car owl-carousel owl-theme">
                    <?php
                    $j = 0;
                    foreach ($product["Images"] as $image) { ?>
                        <div class="owl-img-cont">
                            <div class="item img-canvas <?php echo ($j === 0) ? "img-canvas-active" : ""; ?>" style="background-image: url('/assets/images/<?= $image ?>')"></div>
                        </div>
                        <?php $j++;
                    } ?>
                </div>
                <div class="owl-nav-btn" id="owl-nav-prev" style="display: none;"></div>
                <div class="owl-nav-btn <?php echo count($product["Images"]) < 3 ? "remove" : "" ?>" id="owl-nav-next"></div>
            </div>
        </div>
    </div>

    <form id="cont2" method="POST" action="<?= htmlspecialchars($_SERVER["REQUEST_URI"]) ?>">
        <div id="product-header">
            <h4 id="product-name"><?= $product["Name"] ?></h4>
            <div>
                <p>
                    <span id="price" class="<?= $product["Discount"] ? "line-through" : "highlight" ?>"><?= $product["Price"] ?>€</span>
                    <?php if ($product["Discount"]) { ?>
                        <span id="discounted-price" class="highlight"><?= $product["EndPrice"] ?>€</span>
                    <?php } ?>
                </p>
            </div>
        </div>

        <div id="colors">
                <p class="label">Colori:</p>
                <div id="select">
                    <div id="selected"></div>
                    <div id="select-dropdown" style="display: none;"></div>
                </div>
                <p class="form-error remove" id="color-error" data-error="false">Seleziona un colore</p>
        </div>

        <div id="sizes">
            <p class="label">Taglie:</p>
            <div id="sizes-cont"></div>
            <p class="form-error remove" id="size-error">Seleziona una taglia</p>
        </div>

        <div id="description">
            <p class="label">Descrizione:</p>
            <p><?= $product["Description"] ?></p>
        </div>

        <div id="availability"></div>
        <div id="h"><input type="hidden" name="ProductDetailsID" value=""></div>
        <div id="btn-cont">
            <button id="submit-btn" class="rounded-0 btn btn-white" type="submit" <?php //echo $product["Availability"] === "black" ? "disabled" : ""; ?>>Aggiungi al carrello</button>
        </div>
    </form>

    <div id="cont3">
        <div class="header">
            <p>Prodotti suggeriti</p>
        </div>
        <div id="suggestion-owlcar-cont">
            <div class="suggestion-owlcar owl-carousel owl-theme">
                <?php foreach ($suggestedProds as $prod) { ?>
                    <div class="owl-img-cont">
                        <my-product data-product="<? echo htmlentities(json_encode(
                                                        [
                                                            'id' => $prod["ProductID"],
                                                            'img' => $prod["Images"][0],
                                                            'name' => $prod["Name"],
                                                            'price' => $prod["Price"],
                                                            'discount' =>  $prod["Discount"] ? $prod["Discount"] : null
                                                        ]
                                                    )); ?>">
                        </my-product>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</section>

<script src="/node_modules/jquery/dist/jquery.min.js"></script>
<script src="/node_modules/bootstrap/js/dist/util.js"></script>
<script src="/node_modules/bootstrap/js/dist/carousel.js"></script>
<script src="/node_modules/bootstrap/js/dist/modal.js"></script>
<script src="/node_modules/owl.carousel/dist/owl.carousel.min.js"></script>
<script src="/node_modules/jquery-zoom/jquery.zoom.js"></script>
<script src="/assets/js/product-details.js"></script>
<?php if ($ordered) {
    echo '<script type="text/javascript">$("#product-details-modal").modal("show");</script>';
} ?>

<?php include "views/shared/footer.phtml"; ?>