<?php include "views/shared/account-header.phtml"; ?>

<section id="profile-settings" class="container">
    <div class="modal fade" id="remove-profile-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" id="step-1" role="document">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Sicuro di voler eliminare il profilo?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="rounded-0 btn btn-dark" onclick="$('#remove-profile-modal').modal('hide')">Chiudi</button>
                    <button class="btn btn-danger" id="confirm-remove">Cancella profilo</button>
                </div>
            </div>
        </div>
        <div class="modal-dialog remove" id="step-2" role="document">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Inserire password per confermare</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="/Profilo/Cancella" method="POST">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="password-confirm">Password:</label>
                            <input id="password-confirm" class="form-control rounded-0" type="password" name="Password">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="rounded-0 btn btn-dark" id="step-2-close">Chiudi</button>
                        <input type="hidden" name="UserID" value="<?php echo $_SESSION["User"]["ID"] ?>">
                        <button type="submit" class="btn btn-danger">Conferma</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <form action="/Profilo/Impostazioni" method="POST" class="needs-validation" id="profile-settings-form" novalidate>
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <input type="text" class="form-control rounded-0" id="username" placeholder="Username" value="<?php echo isset($_SESSION["User"]["Username"]) ? $_SESSION["User"]["Username"] : '' ?>" name="Username" pattern="^[a-zA-Z]+(( {1}[a-zA-Z]+)+)?$">
                <div class="invalid-feedback"></div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-12 mb-3">
                <div class="input-group">
                    <input type="email" class="form-control rounded-0" id="email" placeholder="La tua email" value="<?php echo isset($_SESSION["User"]["Email"]) ? $_SESSION["User"]["Email"] : '' ?>" name="Email" aria-describedby="inputGroupPrepend">
                    <div class="invalid-feedback"></div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-12 mb-3">
                <div class="input-group">
                    <input type="password" class="form-control rounded-0" id="password-old" name="Password-old" placeholder="Password precedente">
                    <div class="invalid-feedback"></div>
                </div>
                <div class="input-group">
                    <input type="password" class="form-control rounded-0 mt-2" id="password-new" name="Password-new" placeholder="Nuova password">
                    <div class="invalid-feedback"></div>
                </div>
                <div class="input-group">
                    <input type="password" class="form-control rounded-0 mt-2" id="password-new-confirm" name="Password-new-confirm" placeholder="Conferma nuova password">
                    <div class="invalid-feedback"></div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <button type="submit" class="btn btn-dark rounded-0 col-6 col-xl-5" disabled>Aggiorna</button>
        </div>
        <div class="row justify-content-center">
            <?php if ($updated) { ?>
                <p class="text-success mt-3">Il tuo profilo è stato aggiornato con successo.</p>
            <?php }
        if ($error) { ?>
                <p class="text-danger mt-3"><?= $error ?></p>
            <?php } ?>
        </div>
    </form>
    <div id="remove-profile">
        <div>
            <p class="text-dark" onclick="$('#remove-profile-modal').modal('show')">Rimuovi profilo</p>
        </div>
    </div>
</section>

<script src="/node_modules/jquery/dist/jquery.min.js"></script>
<script src="/node_modules/bootstrap/js/dist/util.js"></script>
<script src="/node_modules/bootstrap/js/dist/modal.js"></script>
<script src="/assets/js/profile-settings.js"></script>

<?php include "views/shared/account-footer.phtml"; ?>