<?php include "views/shared/header.phtml"; ?>

    <section id="signup" class="row justify-content-center align-items-start" class="container">
    <form action="/Crea-Profilo" method="POST" class="needs-validation" novalidate>
            <h2 class="text-center">Crea Profilo</h2>
            <div class="form-group">
                <label for="email">Indirizzo Email</label>
                <input type="email" class="form-control rounded-0" id="email" aria-describedby="email" name="email" placeholder="Inserisci email" required>
                <div class="invalid-feedback"></div>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control rounded-0" id="password" name="password" placeholder="Password" required>
                <div class="invalid-feedback"></div>
            </div>
            <div class="form-group">
                <label for="password-confirm">Conferma Password</label>
                <input type="password" class="form-control rounded-0" id="password-confirm" name="password-confirm" required>
                <div class="invalid-feedback"></div>
            </div>
            <div class="row justify-content-center">
                <button type="submit" id="signup-btn" class="btn btn-white col-6 rounded-0">Crea</button>
            </div>
            <?php if ($error) { ?>
            <div class="row justify-content-center">
                <p class="error"><?= $error ?></p>
            </div>
            <?php } ?>
        </form>
    </section>

    <script src="/assets/js/signup.js"></script>

<?php include "views/shared/footer.phtml"; ?>